name: RTx-Shredder
version: 0.02_01
abstract: RT Shredder Extension
author: Ruslan U. Zakirov <Ruslan.Zakirov@gmail.com>
license: perl
distribution_type: module
build_requires:
  Test::More: 0
  Test::Deep: 0
  DBD::SQLite: 0
  File::Spec: 0
  File::Path: 0
  File::Copy: 0
  Cwd: 0
requires:
  Getopt::Long: 0
  Exception::Class: 0
  IO::String: 0
  Pod::Parser: 0
no_index:
  directory:
    - inc
    - html
generated_by: handwriten
