--- 
abstract: RT Shredder Extension
author: Ruslan U. Zakirov <Ruslan.Zakirov@gmail.com>
build_requires: 
  Cwd: 0
  DBD::SQLite: 0
  File::Copy: 0
  File::Path: 0
  File::Spec: 0
  Test::Deep: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: RTx-Shredder
no_index: 
  directory: 
    - html
    - inc
    - t
requires: 
  DBIx::SearchBuilder: 1.31
  Exception::Class: 1.23
  Getopt::Long: 0
  RT: 3.4
version: 0.07
