name: RTx-Shredder
version: 0.01_01
abstract: RT Shredder Extension
author: Ruslan U. Zakirov <cubic@wildgate.miee.ru>
license: perl
distribution_type: module
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.35
